### ISSUE TITLE
Hover toolbar goes to top and not beside the image container

### ISSUE THREAD

**Issue by gabbydgab** [editor-js/image#271]
I'm using https://cdn.jsdelivr.net/npm/@editorjs/image@latest for this with https://cdn.jsdelivr.net/npm/@editorjs/editorjs@latest

It seems that the image toolbar position is out of place when I try to hover. See sample video. Is there a way we can control this? 

https://www.loom.com/share/d258d2be52674d3c8dc709021148ebac?sid=04d337ec-7973-4427-87ff-4522cacceecb

See config:

![image](https://github.com/user-attachments/assets/dc59171c-9963-43d2-ab8b-3d365588c320)

**Comment by msdoege** [comment]
Just in case anyone else stumbles across this issue:
I had a very similar error that cost me a few hours to fix. In my case, it was because I removed the image block's caption input via 
```css
/* Targeting the Editor.js image caption input */
div.cdx-input.image-tool__caption{
  display: none;
}
```
Turns out, the caption input element is essential for the calculation of the vertical alignment of the Editor.js toolbar (which changed in [v2.30.0](https://github.com/codex-team/editor.js/releases/tag/v2.30.0)). So **instead of removing the caption, I had to hide it** via
```css
/* Targeting the Editor.js image caption input */
div.cdx-input.image-tool__caption {
  visibility: hidden;
  margin-top: -46px;
}
```

By the way, this workaroud of hiding the caption input could be have been avoided, if [this pull request](https://github.com/editor-js/image/pull/96) would have been merged.
